export const TODO_CONSTANTS = {
  ADD_TODO: 'ADD_TODO',
  REMOVE_TODO: 'REMOVE_TODO',
  TOGGLE_TODO_COMPLETED: 'TOGGLE_TODO_COMPLETED',
  TOGGLE_TODO_PRIORITY: 'TOGGLE_TODO_PRIORITY',
  SORT: 'SORT'
};
